@startuml

    class InputTextCommand {
        {static} -description: String
        {static} -keys: List<String>
        {static} -RESOURCE_BUNDLE_NAME: String
        {static} -resourceBundle: ResourceBundle
        +InputTextCommand()
        {static} -getInputText(String): Array<String>
        {static} #updateResourceBundle(): void
        +execute(): void
        +getDescription(): String
        +getKeys(): List<String>
        +update(Observable, Object): void
    }

@enduml
