@startuml

    class SerializeTextCommand {
        {static} -description: String
        {static} -keys: List<String>
        {static} -RESOURCE_BUNDLE_NAME: String
        {static} -resourceBundle: ResourceBundle
        +SerializeTextCommand()
        {static} #updateResourceBundle(): void
        +execute(): void
        +getDescription(): String
        +getKeys(): List<String>
        +update(Observable, Object): void
    }

@enduml
