/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpi_oop_lytvyn07_Application */

#ifndef _Included_ua_khpi_oop_lytvyn07_Application
#define _Included_ua_khpi_oop_lytvyn07_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpi_oop_lytvyn07_Application
 * Method:    system
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ua_khpi_oop_lytvyn07_Application_system
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
