@startuml

    class ShellData {
        -textLines: Array<String>
        ~ShellData()
        +getTextLines(): Array<String>
        +setTextLines(Array<String>): void
        +setTextLines(String[]): void
    }

@enduml
