@startuml

    class ShellData {
        -textLines: List<String>
        ~ShellData()
        +getTextLines(): List<String>
        +setTextLines(List<String>): void
        +setTextLines(String[]): void
    }

@enduml
