@startuml

    class ShellCommandsPool {
        {static} -commands: HashMap<String, AbstractCommand>
        -ShellCommandsPool()
        {static} +getCommand(String): Command
        {static} +getCommandsDescriptions(): Collection<String>
        {static} +getCommandsKeys(): Collection<String>
        {static} +registerCommand(List<String>, Class<?>): boolean
    }

@enduml
