@startuml

    class SQLiteDialectIdentityColumnSupport {
        +SQLiteDialectIdentityColumnSupport()
        +supportsIdentityColumns(): boolean
        +hasDataTypeInIdentityColumn(): boolean
        +getIdentitySelectString(String, String, int): String
        +getIdentityColumnString(int): String
    }

@enduml
