/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpi_oop_lytvyn_util_Console */

#ifndef _Included_ua_khpi_oop_lytvyn_util_Console
#define _Included_ua_khpi_oop_lytvyn_util_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:    ua_khpi_oop_lytvyn_util_Console
 * Method:    system
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ua_khpi_oop_lytvyn_util_Console_system
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
