@startuml

    abstract class AbstractSearchAlgorithm<T> {
        #lastFoundIndex: int
        +AbstractSearchAlgorithm(Comparator<T>)
        +getLastFoundIndex(): int
        #indexNotFound(): int
        +isNull(): boolean
        #isValidArray(T[]): boolean
    }

@enduml
