@startuml

    abstract class AbstractSearchInRangeAlgorithm<T> {
        +AbstractSearchInRangeAlgorithm(Comparator<T>)
        #isValidRange(T[], int, int): boolean
        +search(T[], T): int
    }

@enduml
