@startuml

    class ExponentialSearch<T> {
        -searchInRangeAlgorithm: SearchInRangeAlgorithm<T>
        +ExponentialSearch(AbstractSearchInRangeAlgorithm<T>)
        +ExponentialSearch(Comparator<T>)
        +getSearchInRangeAlgorithm(): SearchInRangeAlgorithm<T>
        +search(T[], T): int
        +setSearchInRangeAlgorithm(SearchInRangeAlgorithm<T>): void
    }

@enduml
