@startuml

    class NullSearchAlgorithm<T> {
        {static} +INSTANCE: SearchAlgorithm
        -NullSearchAlgorithm()
        +getLastFoundIndex(): int
        +search(T[], T): int
        +search(T[], T, int, int): int
    }

@enduml
