@startuml

    namespace ua.khpi.oop.malokhvii04 {

        class Application {
            {static} -DEFAULT_LOCALE: String
            {static} -LOCALES: String[]
            {static} -BASE_PACKAGE: String
            -Application()
            {static} +getApplicationName(): String
            {static} +main(String[]): void
            {static} -setLocales(): void
        }

    }

@enduml
