@startuml

    interface SortAlgorithm<T> {
        {abstract} +isReversedOrder(): boolean
        {abstract} +setReversedOrder(boolean): void
        {abstract} +sort(Array<T>): void
    }

@enduml
