@startuml

    class SQLiteMetadataBuilderInitializer {
        {static} -logger: Logger
        {static} -dialect: SQLiteDialect
        {static} -resolver: DialectResolver
        +SQLiteMetadataBuilderInitializer()
        +contribute(MetadataBuilder, StandardServiceRegistry): void
    }

@enduml
