@startuml

    abstract class AbstractSortAlgorithm<T> {
        #isReversedOrder: boolean
        +AbstractSortAlgorithm(Comparator<T>)
        {static} #swap(T[], int, int): void
        +isNull(): boolean
        +isReversedOrder(): boolean
        +setReversedOrder(boolean): void
        +sort(Collection<T>): T[]
    }

@enduml
