@startuml

    abstract class AbstractSortAlgorithm<T> {
        #isReversedOrder: boolean
        +AbstractSortAlgorithm(Comparator<T>)
        {static} #checkArray(Object[]): boolean
        {static} #checkLength(Object[], int): boolean
        {static} #swap(T[], int, int): void
        +isNull(): boolean
        +isReversedOrder(): boolean
        +setReversedOrder(boolean): void
        +sort(T[]): boolean
    }

@enduml
