@startuml

    class NullSortAlgorithm<T> {
        {static} +INSTANCE: SortAlgorithm
        -NullSortAlgorithm()
        +isReversedOrder(): boolean
        +setReversedOrder(boolean): void
        +sort(T[]): boolean
        +sort(T[], int): boolean
    }

@enduml
