@startuml

    class NullSortAlgorithm<T> {
        {static} +INSTANCE: SortAlgorithm
        -NullSortAlgorithm()
        +isReversedOrder(): boolean
        +setReversedOrder(boolean): void
        +sort(Collection<T>): T[]
        +sort(T[]): void
    }

@enduml
