@startuml

    interface SortAlgorithm<T> {
        {abstract} +isReversedOrder(): boolean
        {abstract} +setReversedOrder(boolean): void
        {abstract} +sort(Collection<T>): T[]
        {abstract} +sort(T[]): void
    }

@enduml
