@startuml

    interface SortAlgorithm<T> {
        {abstract} +isReversedOrder(): boolean
        {abstract} +setReversedOrder(boolean): void
        {abstract} +sort(T[]): boolean
        {abstract} +sort(T[], int): boolean
    }

@enduml
