@startuml

    class TopDownMergeSort<T> {
        +TopDownMergeSort(Comparator<T>)
        -mergeSlices(Object[], Object[]): Object[]
        -mergeSort(Object[]): Object[]
        +sort(T[]): void
    }

@enduml
