@startuml

    class NavigationContext {
        -injector: Injector
        -NavigationContext(PersitenceConfigurationBean)
        {static} +create(PersitenceConfigurationBean): NavigationContext
        +createNavigationService(): NavigationService
        +createPersistService(): PersistService
        +createUnitOfWork(): UnitOfWork
        +getInjector(): Injector
    }

@enduml
