@startuml

    class HelpCommand {
        {static} -description: String
        {static} -keys: List<String>
        {static} -RESOURCE_BUNDLE_NAME: String
        {static} -resourceBundle: ResourceBundle
        +HelpCommand()
        {static} -printCommandDescription(String, String): void
        {static} -updateResourceBundle(): void
        +execute(): void
        +getDescription(): String
        +getKeys(): List<String>
        +update(Observable, Object): void
    }

@enduml
