@startuml

    class ArrayList<E> {
        {static} -DEFAULT_INITIAL_CAPACITY: int
        {static} -serialVersionUID: long
        ~data: Object[]
        +ArrayList()
        +ArrayList(Collection<?>)
        +ArrayList(E[])
        +ArrayList(int)
        +acceptVisitor(ListVisitor<E>): void
        +add(E): boolean
        +add(int, E): boolean
        +addAfter(int, E): boolean
        +addAll(Collection<?>): boolean
        +addAll(E[]): boolean
        +addBefore(int, E): boolean
        +addFirst(E): boolean
        +addLast(E): boolean
        +clear(): void
        -ensureCapacity(int): void
        +get(int): E
        +getFirst(): E
        +getLast(): E
        +indexOf(Object): int
        +iterator(int): List.ListIterator<E>
        #readObject(ObjectInputStream): void
        +remove(int): E
        +remove(Object): boolean
        -removeElement(int): void
        +removeFirst(): E
        +removeLast(): E
        +set(int, E): E
        +setFirst(E): E
        +setLast(E): E
        +toArray(): Object[]
        +toArray(T[]): T[]
        #writeObject(ObjectOutputStream): void
    }

@enduml
