@startuml

    class ArrayList.ArrayListIterator {
        -nextIndex: int
        -ArrayListIterator(int)
        +hasNext(): boolean
        +hasPrevious(): boolean
        +next(): E
        +previous(): E
        +remove(): void
    }

@enduml
