@startuml

    interface CompositeSpecification<T> {
        +getUnsatisfied(T): Set<Specification<T>>
        +getSatisfied(T): Set<Specification<T>>
        +get(int): Specification<T>
        +set(int, Specification<T>): Specification<T>
        +add(Specification<T>): boolean
        +remove(int): Specification<T>
        +iterator(): Iterator<Specification<T>>
        +isSatisfiedBy(T): boolean
    }

@enduml
