@startuml

    class CompositeSpecification.CompositeSpecificationIterator<T> {
        -iterators: Deque<Iterator<Specification<T>>>
        -CompositeSpecificationIterator(Iterator<Specification<T>>)
        +hasNext(): boolean
        +next(): Specification<T>
    }

@enduml
