@startuml

    class DefaultCompositeSpecification<T> {
        {static} -serialVersionUID: long
        ~DefaultCompositeSpecification()
        ~DefaultCompositeSpecification(Iterable<Specification<T>>)
        ~DefaultCompositeSpecification(Specification<T>[])
    }

@enduml
