@startuml

    class SpecificationPair<T> {
        +SpecificationPair(Specification<T>, Specification<T>)
        +setFirst(Specification<T>): Specification<T>
        +setSecond(Specification<T>): Specification<T>
        +getFirst(): Specification<T>
        +getSecond(): Specification<T>
    }

@enduml
