@startuml

    interface Specification<T> {
        +or(Specification<T>): Specification<T>
        +and(Specification<T>): Specification<T>
        +not(): Specification<T>
        +toPredicate(): Predicate<T>
        +toUtilPredicate(): Predicate<T>
        +getSpecifications(): List<Specification<T>>
        +iterator(): Iterator<Specification<T>>
        {abstract} +isSatisfiedBy(T): boolean
    }

@enduml
