@startuml

    interface PersitenceConfigurationBean {
        {abstract} +getPersistenceUnitName(): String
        {abstract} +toProperties(): Properties
        {abstract} +toMappedProperties(): Map<String, String>
    }

@enduml
