@startuml

    enum DefaultSubscribeExceptionHandler {
        {static} +INSTANCE
        -DefaultSubscribeExceptionHandler()
        +handleException(Throwable, SubscriberExceptionContext): void
    }

@enduml
