@startuml

    class SoftSubscriber {
        -subscriber: SoftReference<Object>
        ~SoftSubscriber(Object, Method, EventBus, SubscriberMetadata, SubscribeMetadata)
        +getSubscriber(): Object
    }

@enduml
