@startuml

    class StrongSubcriber {
        -subscriber: Object
        #StrongSubcriber(Object, Method, EventBus, SubscriberMetadata, SubscribeMetadata)
        +getSubscriber(): Object
    }

@enduml
