@startuml

    class SubscriberExceptionContext {
        -event: Object
        -eventBus: EventBus
        -subscriber: Object
        -subscriberMethod: Method
        ~SubscriberExceptionContext(EventBus, Object, Object, Method)
        +getEvent(): Object
        +getEventBus(): EventBus
        +getSubscriber(): Object
        +getSubscriberMethod(): Method
    }

@enduml
