@startuml

    abstract class AbstractDispatcherDecorator {
        -dispatcher: Dispatcher
        #AbstractDispatcherDecorator(Dispatcher)
        +getDispatcher(): Dispatcher
        +setDispatcher(Dispatcher): void
    }

@enduml
