@startuml

    class AsynchronousDispatcher {
        -queue: ConcurrentLinkedQueue<AsynchronousDispatcher.EventWithSubscriber>
        ~AsynchronousDispatcher()
        +dispatch(Object, Iterator<Subscriber>): void
    }

@enduml
