@startuml

    class PerThreadQueuedDispatcher {
        -dispatching: ThreadLocal<Boolean>
        -queue: ThreadLocal<Queue<PerThreadQueuedDispatcher.Event>>
        ~PerThreadQueuedDispatcher()
        +dispatch(Object, Iterator<Subscriber>): void
    }

@enduml
