@startuml

    class AnnotationMetadataException {
        {static} -serialVersionUID: long
        +AnnotationMetadataException()
        +AnnotationMetadataException(String)
        +AnnotationMetadataException(String, Throwable)
        +AnnotationMetadataException(Throwable)
    }

@enduml
