@startuml

    class AnnotationMetadatas {
        -AnnotationMetadatas()
        {static} +newSubscribeMetadata(Method): SubscribeMetadata
        {static} +newSubscriberMetadata(Class<?>): SubscriberMetadata
    }

@enduml
