@startuml

    class SubscriberMetadata {
        -referencePolicy: SubscriberReferencePolicy
        -subscriberType: Class<?>
        ~SubscriberMetadata(Subscriber, Class<?>)
        +getReferencePolicy(): SubscriberReferencePolicy
        +getSubscriberType(): Class<?>
    }

@enduml
