@startuml

    class SubscribeMetadata {
        -eventType: Class<?>
        -priority: int
        ~SubscribeMetadata(Subscribe, Class<?>)
        +getEventType(): Class<?>
        +getPriority(): int
    }

@enduml
