@startuml

    class Anagrams {
        {static} +DEFAUL_WORD_PATTERN: String
        -Anagrams()
        {static} +findAllAnanyms(CharSequence, String): Collection<Ananym>
        {static} +findAllAnanyms(Iterable<CharSequence>): Collection<Ananym>
        {static} +findAllAnanyms(Iterable<CharSequence>, String): Collection<Ananym>
        {static} +findAllAnanymsInString(Iterable<String>): Collection<Ananym>
        {static} +findAllAnanymsInString(Iterable<String>, String): Collection<Ananym>
        {static} +findAllPalindromes(Iterable<CharSequence>): Collection<CharSequence>
        {static} +findAllPalindromes(Iterable<CharSequence>, String): Collection<CharSequence>
        {static} +findAllPalindromesInString(Iterable<String>): Collection<String>
        {static} +findAllPalindromesInString(Iterable<String>, String): Collection<String>
    }

@enduml
