@startuml

    class PolynomialHash {
        {static} -DEFAULT_HASHABLE_CHAR_SEQUENCE_SIZE: int
        {static} -POLYNOMIAL_BASE: int
        {static} -polynomials: long[]
        {static} +ZERO_HASH: long
        -PolynomialHash()
        {static} -calculatePolynomials(int): void
        {static} +charSequenceHash(CharSequence): long
        {static} +reversedCharSequenceHash(CharSequence): long
    }

@enduml
